add_newline = true
#format = """
#[â”Œâ”€â”€â”€â”€](bold white)\\[$directory\\]$hg_branch
#[â””â”€](bold white)$character"""
format = """$git_commit $git_state $git_status
(bold cyan)Î¨ $directory$hg_branch$git_branch
âœ 
"""
right_format = "$status$cmd_duration $username"
scan_timeout = 10

continuation_prompt = "â–¶â–¶"

cmake.disabled = true
cobol.disabled = true
conda.disabled = true
crystal.disabled = true
dart.disabled = true
deno.disabled = true
dotnet.disabled = true
elixir.disabled = true
elm.disabled = true
erlang.disabled = true
golang.disabled = true
helm.disabled = true
java.disabled = true
julia.disabled = true
kotlin.disabled = true
lua.disabled = true
nim.disabled = true
nodejs.disabled = true
ocaml.disabled = true
openstack.disabled = true
perl.disabled = true
php.disabled = true
pulumi.disabled = true
purescript.disabled = true
python.disabled = true
red.disabled = true
rlang.disabled = true
ruby.disabled = true
rust.disabled = true
scala.disabled = true
singularity.disabled = true
swift.disabled = true
terraform.disabled = true
vagrant.disabled = true
vlang.disabled = true
zig.disabled = true

[aws]
symbol = "îŒ½  "
format = '\[[$symbol($profile)(\($region\))(\[$duration\])]($style)\]'

[docker_context]
symbol = "ïŒˆ "
format = '\[[$symbol$context]($style)\]'

[character]
vicmd_symbol = "[â®](bold green)"
success_symbol = "[â¯](bold green)"

[directory]
style="bold cyan"
truncation_length = 8
truncation_symbol = "â€¦/"
repo_root_format="[$before_root_path]($style)[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style) "
read_only="ğŸ”’"
read_only_style="red"
format="[$path]($style)[$read_only]($read_only_style)"

[directory.substitutions]

[package]
format = "via [ğŸ $version](208 bold) "

[[battery.display]]
threshold = 10
style = "bold red"
discharging_symbol = "ğŸ’€ "

[cmd_duration]
min_time = 500
format = "underwent [$duration](bold yellow)"

[status]
style = "bg:blue"
symbol = "ğŸ”´"
format = '[\[$symbol $common_meaning$signal_name$maybe_int\]]($style) '
map_symbol = true
disabled = false

[time]
disabled = false
format = 'ğŸ•™[\[ $time \]]($style) '
time_format = "%T"
utc_time_offset = "-5"
time_range = "10:00:00-14:00:00"

[username]
style_user = "white bold"
style_root = "black bold"
format = "[$user]($style) "
disabled = false
show_always = true

[hg_branch]
format = "\\([ğŸŒ± $branch](bold purple)\\)"
truncation_length = 17
truncation_symbol = ".~."

[git_branch]
symbol = "ï˜"
format = '\[[$symbol$branch]($style)\]'
truncation_length = 17
truncation_symbol = ".~."
ignore_branches = []

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
format = '[\($state( $progress_current of $progress_total)\)]($style) '

[git_status]
conflicted = "âš”ï¸ "
ahead = "ğŸï¸ ğŸ’¨ Ã—${count}"
behind = "ğŸ¢ Ã—${count}"
diverged = "ğŸ”± ğŸï¸ ğŸ’¨ Ã—${ahead_count} ğŸ¢ Ã—${behind_count}"
untracked = "ğŸ›¤ï¸  Ã—${count}"
stashed = "ğŸ“¦ "
modified = "ğŸ“ Ã—${count}"
staged = "ğŸ—ƒï¸  Ã—${count}"
renamed = "ğŸ“› Ã—${count}"
deleted = "ğŸ—‘ï¸  Ã—${count}"
style = "bright-white"
format = "$all_status$ahead_behind"
